Updated README.md
## Because:
pip3 dependencies will default to Markdown==3.0.1

This is no longer compatible with calls in in  `util/build.py`

Error:
Traceback (most recent call last):
  File "util/build.py", line 542, in <module>
    format_files(False)
  File "util/build.py", line 492, in format_files
    format_file(file, skip_up_to_date, max(code_mod, templates_mod))
  File "util/build.py", line 384, in format_file
    body = markdown.markdown(contents, ['extra', 'codehilite', 'smarty'])
TypeError: markdown() takes 1 positional argument but 2 were given